/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : XeroxContext.sm
 */


/**
 * Copyright (c) 2011, salesforce.com, inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided
 * that the following conditions are met:
 *
 *    Redistributions of source code must retain the above copyright notice, this list of conditions and the
 *    following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright notice, this list of conditions and
 *    the following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *    Neither the name of salesforce.com, inc. nor the names of its contributors may be used to endorse or
 *    promote products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * @author hhildebrand
 */


package com.salesforce.ouroboros.spindle;

import java.util.logging.Logger;

public class XeroxContext
    extends statemap.FSMContext
    implements java.io.Serializable
{
private final static Logger log = Logger.getLogger(XeroxContext.class.getCanonicalName());
//---------------------------------------------------------------
// Member methods.
//

    public Logger getLog() {return log;}

    public XeroxContext(Xerox owner)
    {
        super (XeroxFSM.Suspended);

        _owner = owner;
    }

    public XeroxContext(Xerox owner, XeroxState initState)
    {
        super (initState);

        _owner = owner;
    }

    public synchronized void enterStartState()
    {
        getState().Entry(this);
        return;
    }

    public synchronized void connect()
    {
        _transition = "connect";
        getState().connect(this);
        _transition = "";
        return;
    }

    public synchronized void finished()
    {
        _transition = "finished";
        getState().finished(this);
        _transition = "";
        return;
    }

    public synchronized void initiateCopy()
    {
        _transition = "initiateCopy";
        getState().initiateCopy(this);
        _transition = "";
        return;
    }

    public synchronized void writeReady()
    {
        _transition = "writeReady";
        getState().writeReady(this);
        _transition = "";
        return;
    }

    public XeroxState valueOf(int stateId)
        throws ArrayIndexOutOfBoundsException
    {
        return (_States[stateId]);
    }

    public XeroxState getState()
        throws statemap.StateUndefinedException
    {
        if (_state == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((XeroxState) _state);
    }

    protected Xerox getOwner()
    {
        return (_owner);
    }

    public void setOwner(Xerox owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            _owner = owner;
        }

        return;
    }

    private void writeObject(java.io.ObjectOutputStream ostream)
        throws java.io.IOException
    {
        int size =
            (_stateStack == null ? 0 : _stateStack.size());
        int i;

        ostream.writeInt(size);

        for (i = 0; i < size; ++i)
        {
            ostream.writeInt(
                ((XeroxState) _stateStack.get(i)).getId());
        }

        ostream.writeInt(_state.getId());

        return;
    }

    private void readObject(java.io.ObjectInputStream istream)
        throws java.io.IOException
    {
        int size;

        size = istream.readInt();

        if (size == 0)
        {
            _stateStack = null;
        }
        else
        {
            int i;

            _stateStack =
                new java.util.Stack<statemap.State>();

            for (i = 0; i < size; ++i)
            {
                _stateStack.add(i, _States[istream.readInt()]);
            }
        }

        _state = _States[istream.readInt()];

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private Xerox _owner;
    transient private static XeroxState[] _States =
    {
        XeroxFSM.Suspended,
        XeroxFSM.Copy,
        XeroxFSM.Finished,
        XeroxFSM.Handshake,
        XeroxFSM.Initialized,
        XeroxFSM.SendHeader,
        XeroxFSM.Close
    };

    @SuppressWarnings("serial")
    public static abstract class XeroxState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected XeroxState(String name, int id)
        {
            super (name, id);
        }

        protected void Entry(XeroxContext context) {}
        protected void Exit(XeroxContext context) {}

        protected void connect(XeroxContext context)
        {
            Default(context);
        }

        protected void finished(XeroxContext context)
        {
            Default(context);
        }

        protected void initiateCopy(XeroxContext context)
        {
            Default(context);
        }

        protected void writeReady(XeroxContext context)
        {
            Default(context);
        }

        protected void Default(XeroxContext context)
        {
            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //
    }

    /* package */ static abstract class XeroxFSM
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //
        public static final XeroxFSM_Suspended Suspended =
            new XeroxFSM_Suspended("XeroxFSM.Suspended", 7);
        public static final XeroxFSM_Copy Copy =
            new XeroxFSM_Copy("XeroxFSM.Copy", 8);
        public static final XeroxFSM_Finished Finished =
            new XeroxFSM_Finished("XeroxFSM.Finished", 9);
        public static final XeroxFSM_Handshake Handshake =
            new XeroxFSM_Handshake("XeroxFSM.Handshake", 10);
        public static final XeroxFSM_Initialized Initialized =
            new XeroxFSM_Initialized("XeroxFSM.Initialized", 11);
        public static final XeroxFSM_SendHeader SendHeader =
            new XeroxFSM_SendHeader("XeroxFSM.SendHeader", 12);
        public static final XeroxFSM_Close Close =
            new XeroxFSM_Close("XeroxFSM.Close", 13);
        @SuppressWarnings("unused")
        private static final XeroxFSM_Default Default =
            new XeroxFSM_Default("XeroxFSM.Default", -1);

    }

    @SuppressWarnings("serial")
    protected static class XeroxFSM_Default
        extends XeroxState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected XeroxFSM_Default(String name, int id)
        {
            super (name, id);
        }
    //-----------------------------------------------------------
    // Member data.
    //
    }

    @SuppressWarnings("serial")
    private static final class XeroxFSM_Suspended
        extends XeroxFSM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private XeroxFSM_Suspended(String name, int id)
        {
            super (name, id);
        }

        protected void connect(XeroxContext context)
        {


            (context.getState()).Exit(context);
            context.setState(XeroxFSM.Handshake);
            (context.getState()).Entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }

    @SuppressWarnings("serial")
    private static final class XeroxFSM_Copy
        extends XeroxFSM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private XeroxFSM_Copy(String name, int id)
        {
            super (name, id);
        }

        protected void Entry(XeroxContext context)
            {
                Xerox ctxt = context.getOwner();

            ctxt.writeCopy();
            ctxt.selectForWrite();
            return;
        }

        protected void writeReady(XeroxContext context)
        {
            Xerox ctxt = context.getOwner();

            if (!ctxt.copy())
            {
                XeroxState endState = context.getState();

                context.clearState();
                try
                {
                    ctxt.selectForWrite();
                }
                finally
                {
                    context.setState(endState);
                }
            }
            else if (ctxt.inError())
            {

                (context.getState()).Exit(context);
                // No actions.
                context.setState(XeroxFSM.Close);
                (context.getState()).Entry(context);
            }
            else if (ctxt.segmentCopied())
            {

                (context.getState()).Exit(context);
                // No actions.
                context.setState(XeroxFSM.SendHeader);
                (context.getState()).Entry(context);
            }            else
            {
                super.writeReady(context);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }

    @SuppressWarnings("serial")
    private static final class XeroxFSM_Finished
        extends XeroxFSM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private XeroxFSM_Finished(String name, int id)
        {
            super (name, id);
        }

        protected void Entry(XeroxContext context)
            {
                Xerox ctxt = context.getOwner();

            ctxt.finished();
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }

    @SuppressWarnings("serial")
    private static final class XeroxFSM_Handshake
        extends XeroxFSM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private XeroxFSM_Handshake(String name, int id)
        {
            super (name, id);
        }

        protected void writeReady(XeroxContext context)
        {
            Xerox ctxt = context.getOwner();

            if (!ctxt.writeHandshake())
            {
                XeroxState endState = context.getState();

                context.clearState();
                try
                {
                    ctxt.selectForWrite();
                }
                finally
                {
                    context.setState(endState);
                }
            }
            else if (ctxt.inError())
            {

                (context.getState()).Exit(context);
                // No actions.
                context.setState(XeroxFSM.Close);
                (context.getState()).Entry(context);
            }
            else if (ctxt.bufferIsWritten())
            {

                (context.getState()).Exit(context);
                // No actions.
                context.setState(XeroxFSM.SendHeader);
                (context.getState()).Entry(context);
            }            else
            {
                super.writeReady(context);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }

    @SuppressWarnings("serial")
    private static final class XeroxFSM_Initialized
        extends XeroxFSM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private XeroxFSM_Initialized(String name, int id)
        {
            super (name, id);
        }

    //-------------------------------------------------------
    // Member data.
    //
    }

    @SuppressWarnings("serial")
    private static final class XeroxFSM_SendHeader
        extends XeroxFSM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private XeroxFSM_SendHeader(String name, int id)
        {
            super (name, id);
        }

        protected void Entry(XeroxContext context)
            {
                Xerox ctxt = context.getOwner();

            ctxt.sendNextSegment();
            return;
        }

        protected void finished(XeroxContext context)
        {


            (context.getState()).Exit(context);
            context.setState(XeroxFSM.Finished);
            (context.getState()).Entry(context);
            return;
        }

        protected void initiateCopy(XeroxContext context)
        {


            (context.getState()).Exit(context);
            context.setState(XeroxFSM.Copy);
            (context.getState()).Entry(context);
            return;
        }

        protected void writeReady(XeroxContext context)
        {
            Xerox ctxt = context.getOwner();

            if (!ctxt.writeHeader())
            {
                XeroxState endState = context.getState();

                context.clearState();
                try
                {
                    ctxt.selectForWrite();
                }
                finally
                {
                    context.setState(endState);
                }
            }
            else if (ctxt.inError())
            {

                (context.getState()).Exit(context);
                // No actions.
                context.setState(XeroxFSM.Close);
                (context.getState()).Entry(context);
            }
            else if (ctxt.bufferIsWritten())
            {

                (context.getState()).Exit(context);
                // No actions.
                context.setState(XeroxFSM.Copy);
                (context.getState()).Entry(context);
            }            else
            {
                super.writeReady(context);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }

    @SuppressWarnings("serial")
    private static final class XeroxFSM_Close
        extends XeroxFSM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private XeroxFSM_Close(String name, int id)
        {
            super (name, id);
        }

        protected void Entry(XeroxContext context)
            {
                Xerox ctxt = context.getOwner();

            ctxt.close();
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
